# syntax=docker/dockerfile:1
FROM golang:1.24-alpine AS build
WORKDIR /src
ENV GOTOOLCHAIN=auto
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/git-reconciler ./cmd/reconciler

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5
RUN microdnf install -y git tar \
  && microdnf clean all
COPY --from=build /out/git-reconciler /usr/local/bin/git-reconciler
ENTRYPOINT ["/usr/local/bin/git-reconciler"]
